import {
  Thermometer,
  Brain,
  Pill,
  Droplets,
  Activity,
  HeartPulse,
  ShieldPlus,
  Bandage,
  Leaf,
  MessageSquare,
  Eye,
  Dna,
  Heart,
  Venus,
} from 'lucide-react';

export const CATEGORY_ICON_MAP = {
  thermometer: Thermometer,
  brain: Brain,
  pill: Pill,
  droplets: Droplets,
  activity: Activity,
  'heart-pulse': HeartPulse,
  'shield-plus': ShieldPlus,
  bandage: Bandage,
  leaf: Leaf,
  capsules: Pill,
  speech: MessageSquare,
  eye: Eye,
  dna: Dna,
  heart: Heart,
  venus: Venus,
};
